Adding import checking to ruff
microsoft/semantic-kernel pull request #1294
Opened 2023-05-31 22:45 UTC by mkarle

### Motivation and Context

Replacing flake8 and isort with ruff in the pre-commit hook. Adding "I" to ruff rules so that it checks for import errors.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

2023-06-09 21:51 UTC, awharrison-28 approved these changes

2023-06-09 21:53 UTC, awharrison-28 requested changes
I think this PR requires some changes to the linting checks in .github/workflows/lint.yml

2023-06-13 23:05 UTC, awharrison-28 approved these changes

2023-06-13 23:42 UTC, dluc approved these changes

2023-06-13 23:42 UTC, merged