Allow client to provide the OpenAIClient and APIM example
microsoft/semantic-kernel pull request #1446
Opened 2023-06-13 15:31 UTC by markwallace-microsoft

### Motivation and Context

Please help reviewers and future users, providing the following information:
  1. Why is this change required? Demonstrates how to use SK together with Azure API Management
  2. What problem does it solve? Allows a custom OpenAIClient to be created by client code and thereby have full access to `OpenAIClientOptions`
  3. What scenario does it contribute to? Support for customer who want to protect their Azure OpenAI API keys 
  4. If it fixes an open issue, please link to the issue here.

### Description
Allowing the OpenAIClient to be created by the client gives them full access to the `OpenAIClientOptions`.
Consider the case where a developer is using APIM to protect their API keys and starts to see a problem. 
If you run the associated sample with a bad subscription key the trace in will include the following:

```
      Headers:
      ErrorSource: authorization
      ErrorReason: SubscriptionKeyInvalid
      ErrorMessage: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
      ErrorSection: backend
      ErrorStatusCode: 401
```

Without the `Diagnostics` seeting in `OpenAIClientOptions` the trace in will include the following:

```
      Headers:
      ErrorSource: REDACTED
      ErrorReason: REDACTED
      ErrorMessage: REDACTED
      ErrorSection: REDACTED
      ErrorStatusCode: REDACTED
```

### Contribution Checklist
- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

2023-06-14 02:27 UTC, lemillermicrosoft requested changes
LGTM. One change needed. This should help enable some better unit test coverage I think, too!

2023-06-14 02:27 UTC, lemillermicrosoft commented on samples/dotnet/kernel-syntax-examples/Program.cs
> +        /*
```suggestion
```

2023-06-14 02:27 UTC, lemillermicrosoft commented on samples/dotnet/kernel-syntax-examples/Program.cs
> +        */
```suggestion
```

2023-06-15 17:39 UTC, lemillermicrosoft commented on .github/workflows/java-format.yml
> +name: Java format automation
I'm fine with these changes, but are they intentional with this pr?

2023-06-15 17:42 UTC, lemillermicrosoft commented on dotnet/src/Connectors/Connectors.AI.OpenAI/TextEmbedding/AzureTextEmbeddingGeneration.cs
> -/// Azure OpenAI text embedding service.
I think service was the right term we're going with as `ITextEmbeddingGeneration` implements `IAIService`

2023-06-15 17:43 UTC, lemillermicrosoft commented on dotnet/src/Connectors/Connectors.AI.OpenAI/TextEmbedding/AzureTextEmbeddingGeneration.cs
> -/// Azure OpenAI text embedding service.
I see though we were not consistent in this file already. /shrug

2023-06-15 17:43 UTC, lemillermicrosoft commented on python/.conf/.pre-commit-config.yaml
>      hooks:
These changes intentional?

2023-06-16 14:05 UTC, markwallace-microsoft commented on python/.conf/.pre-commit-config.yaml
>      hooks:
Created a new PR: https://github.com/microsoft/semantic-kernel/pull/1520

2023-06-16 14:05 UTC, closed without merging