Python: Correct syntax in core skill examples
microsoft/semantic-kernel pull request #1731
Opened 2023-06-27 11:21 UTC by HenriSchulte-MS

Fix for #1730 
Some core skills include example code showing how to import the skill. Some of these examples, used an invalid syntax where arguments were in the reversed order, e.g. kernel.import_skill("wait", WaitSkill()); instead of the valid kernel.import_skill(WaitSkill(), "wait").

2023-06-27 18:32 UTC, amsacha requested changes
there's a small typo but besides that looks good to me!

2023-06-27 18:32 UTC, amsacha commented on python/semantic_kernel/core_skills/file_io_skill.py
> +        kernel.import_skill(FileIOSkill(), skill_name"file")
```suggestion
        kernel.import_skill(FileIOSkill(), skill_name="file")
```

2023-06-29 16:52 UTC, amsacha approved these changes

2023-06-29 20:18 UTC, shawncal approved these changes

2023-06-29 20:19 UTC, shawncal commented
Good catch. Thanks for the contribution @HenriSchulte-MS!

2023-06-29 20:23 UTC, merged