OpenAPI skills MVP
microsoft/semantic-kernel pull request #188
Opened 2023-03-28 19:27 UTC by SergeyMenshykh

### Motivation and Context

The change lay foundation for OpenApi skills support by introducing a set of classes for importing, parsing OpenApi documents and sending HTTP requests to the resources described in them.

### Description

The PR adds the following classes/methods:
- ImportOpenApiFromDirectoryExtension – discovers OpenAPI document in a folder, creates SKFunction per REST operation in the document, and registers the functions in the Kernel. 
- RegisterOpenApiSkill - reates SKFunction per REST operation in the document, and registers the functions in the Kernel. 
- OpenApiDocumentParser – iterates over the collection of paths in OpenAPI document and creates an instance of RestOperation model class for each of them. 
- RestOperationRunner – accepts an instance of the RestOperation class and collection of arguments. Gets all required components (url, body, headers, …) for HTTP request and sends the request. 
- A few other model, exception, and helper classes.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

2023-03-28 20:06 UTC, umeshma commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestParameterType.cs
There are already part of the Microsoft.OpenApi SDK. All defined here. 
Microsoft.OpenApi.Models.ParameterLocation

2023-03-28 20:09 UTC, shawncal commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
> +    public static IDictionary<string, ISKFunction> RegisterOpenApiSkill(this IKernel kernel, Stream documentStream, string skillName)
We'll want a overload of this that loads directly from a json url, and one from a local file json path (maybe these are the same... both string paths)

2023-03-28 20:15 UTC, umeshma commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestOperation.cs
There is already a OpenApiOperation object.
Microsoft.OpenApi.Models.OpenApiOperation

2023-03-28 20:19 UTC, umeshma commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs
Why duplicate all the parameter information into internal objects? 
I can see why you may want a REST operation, but why duplicate all the parameters and options? Just hold onto all the metadata types already defined in Microsoft.OpenAPI - keep a reference to them.

2023-03-28 20:19 UTC, shawncal commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Skills/LocalOpenApiSkillsProvider.cs
> +    public static Stream LoadFroResource(string skillName)
```suggestion
    public static Stream LoadFromResource(string skillName)
```

2023-03-28 20:19 UTC, shawncal commented on samples/dotnet/kernel-syntax-examples/Example16_OpenApiSkill.cs
> +        kernel.RegisterOpenApiSkill(LocalOpenApiSkillsProvider.LoadFroResource(LocalOpenApiSkillsProvider.AzureKeyVault), LocalOpenApiSkillsProvider.AzureKeyVault);
```suggestion
        kernel.RegisterOpenApiSkill(LocalOpenApiSkillsProvider.LoadFromResource(LocalOpenApiSkillsProvider.AzureKeyVault), LocalOpenApiSkillsProvider.AzureKeyVault);
```

2023-03-28 20:20 UTC, umeshma commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Rest/RestOperationRunner.cs
Where will retry etc. get applied for the HttpClient?

2023-03-28 20:35 UTC, adrianwyatt requested changes

2023-03-28 20:35 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
> +                kernel.Log.LogWarning(ex, "Something went wrong while rendering the Rest function. Function: {0}.{1}. Error: {2}", skillName, operation.Id, ex.Message);
Why not throw?

2023-03-28 20:35 UTC, adrianwyatt commented on samples/dotnet/kernel-syntax-examples/Example16_OpenApiSkill.cs
> +        var plan = await kernel.RunAsync("Load 'test-secret' from Azure KeyValut available at https://dev-tests.vault.azure.net using GetSecret function.", planner["CreatePlan"]);
In the future I would recommend not using the planner for this particular example, so as to keep the concept count limited to what we are trying to show.

2023-03-28 20:43 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Rest/RestOperationRunner.cs
Good callout. This is going into a feature branch for iteration and we'll be taking a look at robustness before merging into main.

2023-03-28 20:55 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestParameter.cs
@SergeyMenshykh  - Umesh has a good point. Though, to keep other work moving forward, I'm happy to bring this into the feature branch as-is if we look at replacing these models with Microsoft.OpenApi. Unless you have other reasons to roll our own.

2023-03-28 23:00 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs
We will evaluate this change in a (near) future change.

2023-03-28 23:01 UTC, adrianwyatt approved these changes

2023-03-28 23:03 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestParameterType.cs
We will evaluate this change in a (near) future change.

2023-03-28 23:03 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestParameter.cs
We will evaluate this change in a (near) future change.

2023-03-28 23:03 UTC, adrianwyatt commented on dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestOperation.cs
We will evaluate this change in a (near) future change.

2023-03-28 23:04 UTC, merged

2023-03-29 03:19 UTC, shawncal commented
@SergeyMenshykh and @adrianwyatt Now that this is in the feature branch (which is great!) I've un-resolved all the unresolved comments so that they can be addressed in a pre-merge PR. Please make sure to note them (or they'll likely all come up again when merging to main).