[DRAFT] [Python] Add conversation summary skill
microsoft/semantic-kernel pull request #278
Opened 2023-04-03 05:55 UTC by kitnhl

### Motivation and Context

### Description

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

2023-04-04 20:18 UTC, jjhenkel commented
Hey thanks for working on this! I know it's in a draft state, but one bit of early feedback: maybe in the Python version we can put those constants w/ the skill? (This will also help reduce conflicts as we have others working on similar skills that used to, in the C# version, store their prompts in a "constants" file.) 

Open to thoughts/feedback!

2023-04-04 20:20 UTC, jjhenkel commented
Oh and as we're evolving things, soon the `sk.extensions.create_*(kernel, ...)` is getting cleaned up to be just `kernel.create_(...)` (so long as you use `Kernel` as the type and not `KernelBase`)

2023-04-05 03:37 UTC, kitnhl commented
Hi Jordan! Some of the prompts are really long and I feel like it's less readable if it's just part of the code file, so I still have them in a constants file for now. Please let me know if you feel strongly the other way and I'll be happy to change it.

2023-04-05 03:39 UTC, kitnhl commented
> Hey thanks for working on this! I know it's in a draft state, but one bit of early feedback: maybe in the Python version we can put those constants w/ the skill? (This will also help reduce conflicts as we have others working on similar skills that used to, in the C# version, store their prompts in a "constants" file.)
> 
> Open to thoughts/feedback!

Hi Jordan! Happy to help! Some of the prompts are really long and I feel like it's less readable if it's just part of the code file, so I still have them in a constants file for now. Please let me know if you feel strongly the other way and I'll be happy to change it.

2023-04-05 18:01 UTC, jjhenkel commented
That sounds good for now @kitnhl! I think we may eventually try and load them from file or something to clean it up, but that can come later. I'll take a look at this PR soon, looks like we may be blocked by some of the partitioning features being missing (I know someone is actively working on that though).

2023-04-06 23:26 UTC, mkarle requested changes
Just some typos. The rest can be done when unblocked by the partitioner.

2023-04-06 23:26 UTC, mkarle commented on python/semantic_kernel/core_skills/conversation_summary_skill.py
> +        name="getConvesationActionItemsAsync",
typo, getConversationActionItemsAsync

2023-04-06 23:26 UTC, mkarle commented on python/semantic_kernel/core_skills/conversation_summary_skill.py
> +    async def get_convesation_action_items_async(
typo here too

2023-04-06 23:26 UTC, mkarle commented on python/semantic_kernel/core_skills/conversation_summary_skill.py
> +    async def get_convesation_topics_async(
typo

2023-04-10 22:09 UTC, mkarle approved these changes

2023-04-10 22:49 UTC, merged