Java: Merge main into java-development
microsoft/semantic-kernel pull request #4042
Opened 2023-12-06 15:30 UTC by dsgrieve

### Motivation and Context

sync java-development branch up with the main branch

### Description

(upstream is microsoft/semantic-kernel)

git fetch upstream main
git fetch upstream java-development
git checkout -b merge-main upstream/java-development
git merge -X ours upsteam/main
git commit -a
git push origin merge-main

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

2023-12-06 15:32 UTC, johnoliver approved these changes

2023-12-06 15:46 UTC, moonbox3 approved these changes

2023-12-06 16:54 UTC, johnoliver requested changes
tmp rejection to block merging

2023-12-07 16:22 UTC, johnoliver approved these changes

2023-12-07 16:23 UTC, moonbox3 approved these changes

2023-12-14 13:08 UTC, closed without merging