Python: Update import HnswAlgorithmConfiguration
microsoft/semantic-kernel pull request #5130
Opened 2024-02-23 15:17 UTC by seb-jul

### Motivation and Context

### Description

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

2024-02-23 21:13 UTC, moonbox3 requested changes

2024-02-23 21:13 UTC, moonbox3 commented on python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py
> +    HnswAlgorithmConfiguration,
The [unit tests](https://github.com/microsoft/semantic-kernel/actions/runs/8021982266/job/21921710484?pr=5130#step:5:32) are failing for Python 3.8.

2024-02-23 21:26 UTC, moonbox3 commented
Does this require a package update to `11.6.0b1`?

2024-02-23 21:37 UTC, seb-jul commented
Yes https://github.com/Azure/azure-sdk-for-python/blob/azure-search-documents_11.6.0b1/sdk/search/azure-search-documents/CHANGELOG.md

2024-02-23 21:42 UTC, seb-jul commented
`11.6.0b1` is a prerelease but I see it's allowed for azure-search-documents

2024-02-23 21:49 UTC, seb-jul commented
@microsoft-github-policy-service agree

2024-02-23 22:07 UTC, moonbox3 commented
Looks like the current code still doesn't play well with Python 3.8.

2024-02-25 00:08 UTC, moonbox3 approved these changes

2024-02-27 07:29 UTC, eavanvalkenburg approved these changes
thanks for keeping this one up to date!

2024-02-27 14:54 UTC, moonbox3 commented
Hi @seb-jul, we had a lot of changes go into master in the last few days. Locally, could you please pull the latest down, merge, and update the poetry lock file as stated [here](https://github.com/microsoft/semantic-kernel/actions/runs/8065936467/job/22035354310?pr=5130#step:6:14)? Thank you!

2024-02-27 18:45 UTC, seb-jul commented
Hello @moonbox3 just pushed updated poetry lock file

2024-02-27 19:59 UTC, eavanvalkenburg commented
@seb-jul can you have a look at the failing tests?

2024-02-27 20:32 UTC, seb-jul commented
https://github.com/microsoft/semantic-kernel/pull/5223 just created another PR sorry

2024-02-27 20:32 UTC, closed without merging