Python: Pass kernel args to tool calls
microsoft/semantic-kernel pull request #5455
Opened 2024-03-12 19:44 UTC by moonbox3

### Motivation and Context

After introducing auto tool calls, they mostly work well for primitive type arguments that are handled by the LLM; however, it may be that the user would like to include other kernel arguments to be used as part of their custom functions, that are of type like KernelArguments.

### Description

This PR combines the kernel arguments plus the required arguments for tool calls. It also includes the kernel function's metadata, which has the kernel arguments while storing the chat message after performing tool calling. 
- This closes #5454 

### Contribution Checklist

- [X] The code builds clean without any errors or warnings
- [X] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [X] All unit tests pass, and I have added new tests where possible
- [X] I didn't break anyone :smile:

2024-03-12 20:15 UTC, juliomenendez requested changes

2024-03-12 20:15 UTC, juliomenendez commented on python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
> +        args_cloned = copy(arguments)
Nothing major but I believe the `.copy` method for dict/list is faster than the `copy` module.

2024-03-12 20:18 UTC, moonbox3 commented on python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
> +        if tool_call_behavior.auto_invoke_kernel_functions and kernel and arguments is None:
I wanted if all are none, but we can move it to your suggestion.

2024-03-12 20:20 UTC, moonbox3 commented on python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
> +        if tool_call_behavior.auto_invoke_kernel_functions and kernel and arguments is None:
Updated

2024-03-12 20:22 UTC, juliomenendez commented on python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
> +        if tool_call_behavior.auto_invoke_kernel_functions and kernel and arguments is None:
If all are none wouldn't catch the case where kernel or arguments are none, right?

2024-03-12 20:24 UTC, moonbox3 commented on python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
> +        if tool_call_behavior.auto_invoke_kernel_functions and kernel and arguments is None:
Yeah good point, thanks.

2024-03-12 20:41 UTC, markwallace-microsoft commented
<!-- Pytest Coverage Comment: python-tests-coverage | python-3.8 -->
<a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/README.md"><img alt="Py3.8 Test Coverage" src="https://img.shields.io/badge/Py3.8 Test Coverage-80%25-green.svg" /></a><details><summary>Python 3.8 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py">open_ai_chat_completion_base.py</a></td><td>159</td><td>62</td><td>61%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L100">100</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L116-L119">116&ndash;119</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L121-L124">121&ndash;124</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L141-L144">141&ndash;144</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L153-L156">153&ndash;156</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L166-L189">166&ndash;189</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L198-L200">198&ndash;200</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L217-L219">217&ndash;219</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L242">242</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L250">250</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L256-L262">256&ndash;262</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L273-L279">273&ndash;279</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L315-L321">315&ndash;321</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L337">337</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L343-L345">343&ndash;345</a></td></tr><tr><td colspan="5"><b>semantic_kernel/functions</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function.py">kernel_function.py</a></td><td>57</td><td>2</td><td>96%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function.py#L119">119</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function.py#L138">138</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function_from_prompt.py">kernel_function_from_prompt.py</a></td><td>123</td><td>3</td><td>98%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function_from_prompt.py#L164">164</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function_from_prompt.py#L191">191</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/functions/kernel_function_from_prompt.py#L287">287</a></td></tr><tr><td colspan="5"><b>semantic_kernel/planners/function_calling_stepwise_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py">function_calling_stepwise_planner.py</a></td><td>92</td><td>33</td><td>64%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py#L115-L166">115&ndash;166</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/4d9abec85681ece38fb879a2fb24dc5f081f2638/python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py#L197-L202">197&ndash;202</a></td></tr><tr><td><b>TOTAL</b></td><td><b>5044</b></td><td><b>990</b></td><td><b>80%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.8 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1059 | 11 :zzz: | 0 :x: | 0 :fire: | 23.140s :stopwatch: |

2024-03-13 08:30 UTC, eavanvalkenburg requested changes
small note, but overall looks good!

2024-03-13 08:30 UTC, eavanvalkenburg commented on python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
> +                args_cloned.update(tool_call.function.parse_arguments())
might be good to have parse_arguments in a seperate try except block, or to add a specific except for the one returned by parse_args, with auto invoke that can then be fed back to the model.

2024-03-13 13:26 UTC, juliomenendez approved these changes

2024-03-13 13:40 UTC, eavanvalkenburg approved these changes
Love it!

2024-03-13 13:49 UTC, eavanvalkenburg approved these changes

2024-03-13 14:00 UTC, merged