.Net Concepts Readme Update
microsoft/semantic-kernel pull request #6117
Opened 2024-05-03 15:43 UTC by RogerBarreto

### Motivation and Context

- Improve search results of our concept examples

2024-05-03 15:46 UTC, sophialagerkranspandey requested changes
Should the resource section be called out in this table?

2024-05-03 17:52 UTC, RogerBarreto commented
I removed as this ones are used by the tests, and probably looking for them will happen in the IDE directly, not thru Github UI.

2024-05-06 23:59 UTC, crickman approved these changes

2024-05-07 17:01 UTC, westey-m approved these changes

2024-05-07 17:02 UTC, westey-m commented on dotnet/samples/Concepts/README.md
> +- [ComplexChat_NestedShopper](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/Agents/ComplexChat_NestedShopper.cs)
Consider using relative paths for these, similar to the agents readme link above.

2024-05-07 17:07 UTC, merged